spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/seomarket
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

---